name: todo_app
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

# This constraint is required for modern Flutter projects.
# It specifies which Dart SDK versions your project is compatible with.
environment:
  sdk: '>=3.2.3 <4.0.0'

# These are the packages your application needs to run.
dependencies:
  flutter:
    sdk: flutter
  
  # For State Management
  flutter_riverpod: ^2.4.9
  
  # For Local Database (Persistence)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # For generating unique IDs for new to-do items
  uuid: ^4.3.3 
  
  # Standard iOS style icons
  cupertino_icons: ^1.0.2

# These packages are only used during development (e.g., for code generation or testing).
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # For Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  
  # Recommended linter for static analysis and code style.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true