// lib/constants/enums.dart

import 'package:hive/hive.dart';

part 'enums.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1)
enum Priority {
  @HiveField(0)
  low,

  @HiveField(1)
  medium,

  @HiveField(2)
  high,
}

@HiveType(typeId: 2)
enum Category {
  @HiveField(0)
  work,

  @HiveField(1)
  personal,

  @HiveField(2)
  shopping,
}